import axios from "axios";

const HttpClient = () => {
  const token =
    "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1MktsazJHZGVucWxmMGxocVVfQV9NWTI2R1p6MjZ0QVVabkVrLWRQYjBVIn0.eyJleHAiOjE3MTcwODkyNjgsImlhdCI6MTcxNzA3MTI2OCwianRpIjoiMGQzYzBiMmYtOTQxOC00MzZhLTg5YWEtZjBkZWM0ZWY4M2Y2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJnYW1lIiwiYWRtaW4tY2xpIiwiYnJva2VyIiwiYWNjb3VudCJdLCJzdWIiOiI0ZDgzMDgyNS0yN2RjLTQ4YjktOWRkOC1iNDA5NWUyNjkzNmEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJkZW1vcyIsInNlc3Npb25fc3RhdGUiOiJhZWNiNDRmYS1jNTI2LTQ2ZjItOGMwYi1lYWIyZTk5YTUyMTMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWRtaW4iLCJIUiIsImRlZmF1bHQtcm9sZXMtZGVtbyIsIlVTRVIiLCJUV08iLCJ3YW5kaSIsInN1cGVyX2FkbWluIiwiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJBQkRJIiwiUk9MRV9BRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIiwiQURNSU4iLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGVtb3MiOnsicm9sZXMiOlsidW1hX3Byb3RlY3Rpb24iLCJUV08iXX0sInJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiZ2FtZSI6eyJyb2xlcyI6WyJBRE1JTiIsIlVTRVIiXX0sImFkbWluLWNsaSI6eyJyb2xlcyI6WyJPTkUiLCJUV08iXX0sImJyb2tlciI6eyJyb2xlcyI6WyJyZWFkLXRva2VuIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1hcHBsaWNhdGlvbnMiLCJ2aWV3LWNvbnNlbnQiLCJ2aWV3LWdyb3VwcyIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwiZGVsZXRlLWFjY291bnQiLCJtYW5hZ2UtY29uc2VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImFlY2I0NGZhLWM1MjYtNDZmMi04YzBiLWVhYjJlOTlhNTIxMyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoidXNlciB1c2VyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlciIsImdpdmVuX25hbWUiOiJ1c2VyIiwiZmFtaWx5X25hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSJ9.jal8Opy1Ey0Yhixp8cmlA3qUO9iANRObK-sJWrvRjlVDXxAHYL3na78gdplyXb5-3Z6fd_Q9XH-z_Bo-lLnNCwWQKou8Xs7kx33_-sLI751JuU8NuJdWCbP_XglgEmvoZQ8mwEAsPCO2ST8NXCzbWvG9csOPs-3wiPJMk-rgz8tMNdT2DEQY4BJcIlCRBJJ-oYaS1Ofc3uPymegkStePBwB9BrWtiFa31H58GeSpXVCzdjVurNpEmnJx6Xc7-qowo1giGBDKOuT74BPtGdf2FkBOUS1Av1Rlor5UVMH53ZfcYDK50XBfW92Kuji8N4lh9fPuHPnOowD88Mjz-Rfoug";

  const api = axios.create({
    baseURL:
      "https://mg23lzv4-9909.uks1.devtunnels.ms/organization-structure/api",
    headers: {
      "Content-Type": "application/json",
    },
  });

  // Axios interceptor to attach the token to each request
  api.interceptors.request.use(
    (config) => {
      config.headers.Authorization = `Bearer ${token}`;

      return config;
    },
    (error) => {
      return Promise.reject(error);
    }
  );

  return api;
};

export default HttpClient;
