import axios from "axios";

const HttpClient = () => {
  const token =
    "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGTUx5VHBFVWJQTmtxR2JUdVJsWnR6Z3NHN2tiWU15VDZQNnNDbzN4VHFJIn0.eyJleHAiOjE3MTU5NjQ3NTIsImlhdCI6MTcxNTkyODc1MywianRpIjoiNDQ1NThkNDUtMjZhOC00Yjg0LWEyNmEtY2QxYjcwMjc3ZDc4IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kZW1vIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJnYW1lIiwiYWRtaW4tY2xpIiwiYnJva2VyIiwiYWNjb3VudCJdLCJzdWIiOiI4OWM5ZDVmZC1iN2U5LTQ0NTEtOTkwOC01YzZiMGUxZDdjMWQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJkZW1vcyIsInNlc3Npb25fc3RhdGUiOiJlYzY1ZTQwYi1hMWVlLTRmMDgtYTlhYi0wZTFlOGQ2MzM3OWEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWRtaW4iLCJIUiIsImRlZmF1bHQtcm9sZXMtZGVtbyIsIlVTRVIiLCJUV08iLCJ3YW5kaSIsInN1cGVyX2FkbWluIiwiUk9MRV9VU0VSIiwib2ZmbGluZV9hY2Nlc3MiLCJBQkRJIiwiUk9MRV9BRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIiwiQURNSU4iLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGVtb3MiOnsicm9sZXMiOlsidW1hX3Byb3RlY3Rpb24iLCJUV08iXX0sInJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiZ2FtZSI6eyJyb2xlcyI6WyJBRE1JTiIsIlVTRVIiXX0sImFkbWluLWNsaSI6eyJyb2xlcyI6WyJPTkUiLCJUV08iXX0sImJyb2tlciI6eyJyb2xlcyI6WyJyZWFkLXRva2VuIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1hcHBsaWNhdGlvbnMiLCJ2aWV3LWNvbnNlbnQiLCJ2aWV3LWdyb3VwcyIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwiZGVsZXRlLWFjY291bnQiLCJtYW5hZ2UtY29uc2VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImVjNjVlNDBiLWExZWUtNGYwOC1hOWFiLTBlMWU4ZDYzMzc5YSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoidXNlciB1c2VyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlciIsImdpdmVuX25hbWUiOiJ1c2VyIiwiZmFtaWx5X25hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSJ9.yol5KQhAZta48WG9SJf_NLn5kIieXY4wUJtTsbcHn-X64djK4Y9hUjLdgGKyFvivvbtrxME_fNuiXR4xQatKmI-pTJdVhqabw_bvvRWivY7q2RLJzypDltxSVlbgXkuhOSsXxaHaGwMWvU3SH9fT3ctfYvYg2kd8P80Ub5M1hRnUmlSC6qmdpE_odjovCWz2FvW4Nx3ZRP-GmyZTkOpBJO-BP5MHG0TuuSNY41AbpscY4uU1dmTfUT7okdpJYNl9NmFgC21Fs-82u4T9fNqKMtmlG4orIlFDGpNKxDJw23ECeSZskfeoCLZ9eNTRYgthtAMiFVksZYSOmy8bJpM27w";
  const api = axios.create({
    baseURL:
      "https://mg23lzv4-9909.uks1.devtunnels.ms/organization-structure/api",
    headers: {
      "Content-Type": "application/json",
    },
  });

  // Axios interceptor to attach the token to each request
  api.interceptors.request.use(
    (config) => {
      config.headers.Authorization = `Bearer ${token}`;

      return config;
    },
    (error) => {
      return Promise.reject(error);
    }
  );

  return api;
};

export default HttpClient;
